import { createI18n } from '@genoffice/i18n'

/**
 * Shell main-process UI strings (menus, dialogs, errors), in every supported
 * locale. Extracted verbatim from index.ts as the first slice of the God-file
 * split (audit DESKTOP-P0-01) — this dictionary alone was ~55% of the file.
 */
export const homeI18n = createI18n({
  zh: {
    menuFile: '文件',
    menuSectionNew: '新建',
    untitledDeck: '未命名画布',
    menuNewSlide: '新建画布',
    menuExportPdf: '导出为 PDF…',
    menuOpenInDocs: '转换为 Docs 文档并打开',
    menuPrint: '打印…',
    menuOpen: '打开…',
    menuSave: '保存',
    menuSaveAs: '另存为…',
    menuClose: '关闭',
    menuEdit: '编辑',
    menuWindow: '窗口',
    menuHome: '首页',
    backToHome: '返回首页',
    dlgOpenTitle: '打开文件',
    filterSupported: '支持的文件',
    errBadArgs: '参数无效',
    errBadName: '文件名不合法',
    errMissing: '文件不存在',
    errExists: '同名文件已存在',
    errRenameFailed: '重命名失败',
    errNewTabFailed: '新建文档失败',
    errUnsupportedExt: '暂不支持 .{ext} 类型',
    copySuffix: '副本',
    menuHelp: '帮助',
    thirdPartyNotices: '第三方软件声明',
    menuExportDocx: '导出为 Word…',
    btnCancel: '取消',
    pdfDocxFailedMsg: '导出为 Word 失败',
    pdfDocxBusyMsg: '正在转换中，请等待当前导出完成。',
    menuExportDocxLocal: '导出为 Word（本地转换）…',
    menuExportPptx: '导出为 PPT…',
    pdfPptxFailedMsg: '导出为 PPT 失败',
    pdfPptxBusyMsg: '正在转换中，请等待当前导出完成。',
    pdfPptxLocalScannedDetail: '本地转换已按图片保真导出各页，幻灯片中的文字不可编辑。',
    menuExportXlsx: '导出为 Excel…',
    pdfXlsxFailedMsg: '导出为 Excel 失败',
    pdfXlsxBusyMsg: '正在转换中，请等待当前导出完成。',
    pdfXlsxLocalScannedDetail: '扫描页无法转换为单元格，对应工作表中已写入提示行。',
    pdfXlsxLocalSkippedMsg: '部分页面未转换为单元格',
    pdfXlsxLocalSkippedDetail: '第 {pages} 页无法转换为单元格，对应工作表中已写入提示行。',
    pdfDocxLocalScannedMsg: '检测到扫描件',
    pdfDocxLocalScannedDetail:
      '本地转换已按图片保真导出各页。如需可编辑的文本，请使用云端转换（支持 OCR）。',
    pdfDocxLocalDegradedMsg: '部分页面已按图片导出',
    pdfDocxLocalDegradedDetail: '第 {pages} 页版面无法可靠重建，已按整页图片保真导出。',
    pdfDocxLocalOcrMsg: '扫描页已转换为可编辑文本',
    pdfDocxLocalOcrDetail:
      '第 {pages} 页为扫描件，已通过本地 OCR 识别为可编辑文字，建议校对识别结果。',
    pdfDocxLocalEncryptedDetail: '此 PDF 已加密，未提供正确的密码，无法转换。',
    pdfDocxLocalUnsupportedEncDetail:
      '该文件使用证书加密或不支持的加密方式，无法在本地转换，可尝试云端转换。',
    pdfPwdTitle: '输入密码',
    pdfPwdPrompt: '此 PDF 已加密，请输入打开密码：',
    pdfPwdRetryPrompt: '密码不正确，请重试。',
    pdfPwdOk: '确定',
    pdfPwdVerifying: '正在验证密码…',
    pdfPwdLabel: '密码',
    pdfPwdPlaceholder: '输入打开密码',
    pdfPwdShow: '显示密码',
    pdfPwdHide: '隐藏密码',
    pdfDocxLocalCorruptDetail: '文件已损坏或不是有效的 PDF，无法转换。',
    dlgPickSaveDir: '选择默认保存位置',
    errSaveDirUnusable: '所选文件夹不可写，无法用作默认保存位置',
  },
  en: {
    menuFile: 'File',
    menuSectionNew: 'New',
    untitledDeck: 'Untitled Canvas',
    menuNewSlide: 'New Canvas',
    menuExportPdf: 'Export as PDF…',
    menuOpenInDocs: 'Convert and Open in Docs',
    menuPrint: 'Print…',
    menuOpen: 'Open…',
    menuSave: 'Save',
    menuSaveAs: 'Save As…',
    menuClose: 'Close',
    menuEdit: 'Edit',
    menuWindow: 'Window',
    menuHome: 'Home',
    backToHome: 'Back to Home',
    dlgOpenTitle: 'Open File',
    filterSupported: 'Supported Files',
    errBadArgs: 'Invalid arguments',
    errBadName: 'Invalid file name',
    errMissing: 'File not found',
    errExists: 'A file with that name already exists',
    errRenameFailed: 'Rename failed',
    errNewTabFailed: 'Could not create the new document',
    errUnsupportedExt: '.{ext} files are not supported',
    copySuffix: 'copy',
    menuHelp: 'Help',
    thirdPartyNotices: 'Third-Party Notices',
    menuExportDocx: 'Export as Word…',
    btnCancel: 'Cancel',
    pdfDocxFailedMsg: 'Export as Word failed',
    pdfDocxBusyMsg: 'A Word export is already in progress. Please wait for it to finish.',
    menuExportDocxLocal: 'Export as Word (Local)…',
    menuExportPptx: 'Export as PowerPoint…',
    pdfPptxFailedMsg: 'Export as PowerPoint failed',
    pdfPptxBusyMsg: 'An export is already in progress. Please wait for it to finish.',
    pdfPptxLocalScannedDetail:
      'Each page was exported as a full-page image; the text on the slides is not editable.',
    menuExportXlsx: 'Export as Excel…',
    pdfXlsxFailedMsg: 'Export as Excel failed',
    pdfXlsxBusyMsg: 'An export is already in progress. Please wait for it to finish.',
    pdfXlsxLocalScannedDetail:
      "Scanned pages cannot be converted to cells; each page's worksheet carries a notice row instead.",
    pdfXlsxLocalSkippedMsg: 'Some pages were not converted to cells',
    pdfXlsxLocalSkippedDetail:
      'Pages {pages} could not be converted to cells; their worksheets carry a notice row instead.',
    pdfDocxLocalScannedMsg: 'Scanned document detected',
    pdfDocxLocalScannedDetail:
      'The local conversion exported the pages as images to preserve their appearance. For editable text, use the cloud conversion (with OCR).',
    pdfDocxLocalDegradedMsg: 'Some pages were exported as images',
    pdfDocxLocalDegradedDetail:
      'Page(s) {pages} could not be reliably reconstructed and were exported as full-page images.',
    pdfDocxLocalOcrMsg: 'Scanned pages converted to editable text',
    pdfDocxLocalOcrDetail:
      'Page(s) {pages} were scans; their text was recovered with on-device OCR. Please proofread the result.',
    pdfDocxLocalEncryptedDetail:
      'This PDF is encrypted and could not be opened without the correct password.',
    pdfDocxLocalUnsupportedEncDetail:
      'This PDF uses certificate-based or otherwise unsupported encryption and cannot be converted locally. Try the cloud conversion instead.',
    pdfPwdTitle: 'Enter Password',
    pdfPwdPrompt: 'This PDF is encrypted. Enter the password to open it:',
    pdfPwdRetryPrompt: 'Incorrect password. Please try again.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Verifying password…',
    pdfPwdLabel: 'Password',
    pdfPwdPlaceholder: 'Enter the open password',
    pdfPwdShow: 'Show password',
    pdfPwdHide: 'Hide password',
    pdfDocxLocalCorruptDetail: 'The file is damaged or not a valid PDF and cannot be converted.',
    dlgPickSaveDir: 'Choose Default Save Location',
    errSaveDirUnusable:
      'The selected folder is not writable and cannot be used as the default save location',
  },
  ja: {
    menuFile: 'ファイル',
    menuSectionNew: '新規作成',
    untitledDeck: '無題のキャンバス',
    menuNewSlide: '新規キャンバス',
    menuExportPdf: 'PDF として書き出す…',
    menuOpenInDocs: 'Docs 文書に変換して開く',
    menuPrint: '印刷…',
    menuOpen: '開く…',
    menuSave: '保存',
    menuSaveAs: '名前を付けて保存…',
    menuClose: '閉じる',
    menuEdit: '編集',
    menuWindow: 'ウィンドウ',
    menuHome: 'ホーム',
    backToHome: 'ホームに戻る',
    dlgOpenTitle: 'ファイルを開く',
    filterSupported: '対応ファイル',
    errBadArgs: '引数が無効です',
    errBadName: 'ファイル名が無効です',
    errMissing: 'ファイルが見つかりません',
    errExists: '同名のファイルが既に存在します',
    errRenameFailed: '名前の変更に失敗しました',
    errNewTabFailed: '新規ドキュメントを作成できませんでした',
    errUnsupportedExt: '.{ext} 形式には対応していません',
    copySuffix: 'コピー',
    menuHelp: 'ヘルプ',
    thirdPartyNotices: 'サードパーティソフトウェアに関する通知',
    menuExportDocx: 'Word として書き出す…',
    btnCancel: 'キャンセル',
    pdfDocxFailedMsg: 'Word への書き出しに失敗しました',
    pdfDocxBusyMsg: 'Word への書き出しが進行中です。完了までお待ちください。',
    menuExportDocxLocal: 'Word として書き出す（ローカル変換）…',
    menuExportPptx: 'PowerPoint として書き出す…',
    pdfPptxFailedMsg: 'PowerPoint への書き出しに失敗しました',
    pdfPptxBusyMsg: '変換が進行中です。現在の書き出しが完了するまでお待ちください。',
    pdfPptxLocalScannedDetail:
      '各ページは画像として書き出されたため、スライド内のテキストは編集できません。',
    menuExportXlsx: 'Excel として書き出す…',
    pdfXlsxFailedMsg: 'Excel への書き出しに失敗しました',
    pdfXlsxBusyMsg: '変換が進行中です。現在の書き出しが完了するまでお待ちください。',
    pdfXlsxLocalScannedDetail:
      'スキャンされたページはセルに変換できないため、各ページのワークシートに通知行を書き込みました。',
    pdfXlsxLocalSkippedMsg: '一部のページはセルに変換されませんでした',
    pdfXlsxLocalSkippedDetail:
      'ページ {pages} はセルに変換できなかったため、対応するワークシートに通知行を書き込みました。',
    pdfDocxLocalScannedMsg: 'スキャン文書を検出しました',
    pdfDocxLocalScannedDetail:
      'ローカル変換では、見た目を保つため各ページを画像として書き出しました。編集可能なテキストが必要な場合は、クラウド変換（OCR 対応）をご利用ください。',
    pdfDocxLocalDegradedMsg: '一部のページを画像として書き出しました',
    pdfDocxLocalDegradedDetail:
      'ページ {pages} はレイアウトを正確に再構築できなかったため、ページ全体を画像として書き出しました。',
    pdfDocxLocalOcrMsg: 'スキャンページを編集可能なテキストに変換しました',
    pdfDocxLocalOcrDetail:
      'ページ {pages} はスキャン画像のため、ローカル OCR でテキストを復元しました。内容の確認をおすすめします。',
    pdfDocxLocalEncryptedDetail:
      'このPDFは暗号化されており、正しいパスワードがないため変換できませんでした。',
    pdfDocxLocalUnsupportedEncDetail:
      'このPDFは証明書ベースまたは未対応の暗号化方式を使用しているため、ローカルでは変換できません。クラウド変換をお試しください。',
    pdfPwdTitle: 'パスワードを入力',
    pdfPwdPrompt: 'このPDFは暗号化されています。開くためのパスワードを入力してください：',
    pdfPwdRetryPrompt: 'パスワードが正しくありません。もう一度お試しください。',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'パスワードを確認しています…',
    pdfPwdLabel: 'パスワード',
    pdfPwdPlaceholder: '開くパスワードを入力',
    pdfPwdShow: 'パスワードを表示',
    pdfPwdHide: 'パスワードを非表示',
    pdfDocxLocalCorruptDetail: 'ファイルが破損しているか有効なPDFではないため、変換できません。',
    dlgPickSaveDir: '既定の保存先を選択',
    errSaveDirUnusable:
      '選択したフォルダーは書き込みできないため、既定の保存先として使用できません',
  },
  ko: {
    menuFile: '파일',
    menuSectionNew: '새로 만들기',
    untitledDeck: '제목 없는 캔버스',
    menuNewSlide: '새 캔버스',
    menuExportPdf: 'PDF로 내보내기…',
    menuOpenInDocs: 'Docs 문서로 변환하여 열기',
    menuPrint: '인쇄…',
    menuOpen: '열기…',
    menuSave: '저장',
    menuSaveAs: '다른 이름으로 저장…',
    menuClose: '닫기',
    menuEdit: '편집',
    menuWindow: '창',
    menuHome: '홈',
    backToHome: '홈으로 돌아가기',
    dlgOpenTitle: '파일 열기',
    filterSupported: '지원되는 파일',
    errBadArgs: '잘못된 인수입니다',
    errBadName: '파일 이름이 잘못되었습니다',
    errMissing: '파일을 찾을 수 없습니다',
    errExists: '같은 이름의 파일이 이미 있습니다',
    errRenameFailed: '이름 바꾸기에 실패했습니다',
    errNewTabFailed: '새 문서를 만들지 못했습니다',
    errUnsupportedExt: '.{ext} 형식은 지원되지 않습니다',
    copySuffix: '복사본',
    menuHelp: '도움말',
    thirdPartyNotices: '타사 소프트웨어 고지',
    menuExportDocx: 'Word로 내보내기…',
    btnCancel: '취소',
    pdfDocxFailedMsg: 'Word로 내보내기 실패',
    pdfDocxBusyMsg: 'Word 내보내기가 이미 진행 중입니다. 완료될 때까지 기다려 주세요.',
    menuExportDocxLocal: 'Word로 내보내기(로컬 변환)…',
    menuExportPptx: 'PowerPoint로 내보내기…',
    pdfPptxFailedMsg: 'PowerPoint 내보내기 실패',
    pdfPptxBusyMsg: '변환이 진행 중입니다. 현재 내보내기가 완료될 때까지 기다려 주세요.',
    pdfPptxLocalScannedDetail:
      '각 페이지가 이미지로 내보내져 슬라이드의 텍스트를 편집할 수 없습니다.',
    menuExportXlsx: 'Excel로 내보내기…',
    pdfXlsxFailedMsg: 'Excel 내보내기 실패',
    pdfXlsxBusyMsg: '변환이 진행 중입니다. 현재 내보내기가 완료될 때까지 기다려 주세요.',
    pdfXlsxLocalScannedDetail:
      '스캔된 페이지는 셀로 변환할 수 없어 각 페이지의 워크시트에 알림 행을 기록했습니다.',
    pdfXlsxLocalSkippedMsg: '일부 페이지가 셀로 변환되지 않았습니다',
    pdfXlsxLocalSkippedDetail:
      '{pages} 페이지는 셀로 변환할 수 없어 해당 워크시트에 알림 행을 기록했습니다.',
    pdfDocxLocalScannedMsg: '스캔 문서가 감지되었습니다',
    pdfDocxLocalScannedDetail:
      '로컬 변환은 모양을 유지하기 위해 각 페이지를 이미지로 내보냈습니다. 편집 가능한 텍스트가 필요하면 클라우드 변환(OCR 지원)을 사용하세요.',
    pdfDocxLocalDegradedMsg: '일부 페이지가 이미지로 내보내졌습니다',
    pdfDocxLocalDegradedDetail:
      '{pages}쪽은 레이아웃을 안정적으로 재구성할 수 없어 전체 페이지 이미지로 내보냈습니다.',
    pdfDocxLocalOcrMsg: '스캔 페이지를 편집 가능한 텍스트로 변환했습니다',
    pdfDocxLocalOcrDetail:
      '{pages}페이지는 스캔 이미지로, 로컬 OCR로 텍스트를 복원했습니다. 결과를 검토해 주세요.',
    pdfDocxLocalEncryptedDetail:
      '이 PDF는 암호화되어 있으며 올바른 비밀번호가 없어 변환할 수 없습니다.',
    pdfDocxLocalUnsupportedEncDetail:
      '이 PDF는 인증서 기반이거나 지원되지 않는 암호화 방식을 사용하므로 로컬에서 변환할 수 없습니다. 클라우드 변환을 사용해 보세요.',
    pdfPwdTitle: '비밀번호 입력',
    pdfPwdPrompt: '이 PDF는 암호화되어 있습니다. 열기 위한 비밀번호를 입력하세요:',
    pdfPwdRetryPrompt: '비밀번호가 올바르지 않습니다. 다시 시도하세요.',
    pdfPwdOk: '확인',
    pdfPwdVerifying: '비밀번호 확인 중…',
    pdfPwdLabel: '암호',
    pdfPwdPlaceholder: '열기 암호 입력',
    pdfPwdShow: '암호 표시',
    pdfPwdHide: '암호 숨기기',
    pdfDocxLocalCorruptDetail: '파일이 손상되었거나 유효한 PDF가 아니어서 변환할 수 없습니다.',
    dlgPickSaveDir: '기본 저장 위치 선택',
    errSaveDirUnusable: '선택한 폴더에 쓸 수 없어 기본 저장 위치로 사용할 수 없습니다',
  },
  fr: {
    menuFile: 'Fichier',
    menuSectionNew: 'Nouveau',
    untitledDeck: 'Toile sans titre',
    menuNewSlide: 'Nouvelle toile',
    menuExportPdf: 'Exporter en PDF…',
    menuOpenInDocs: 'Convertir et ouvrir dans Docs',
    menuPrint: 'Imprimer…',
    menuOpen: 'Ouvrir…',
    menuSave: 'Enregistrer',
    menuSaveAs: 'Enregistrer sous…',
    menuClose: 'Fermer',
    menuEdit: 'Édition',
    menuWindow: 'Fenêtre',
    menuHome: 'Accueil',
    backToHome: "Retour à l'accueil",
    dlgOpenTitle: 'Ouvrir un fichier',
    filterSupported: 'Fichiers pris en charge',
    errBadArgs: 'Arguments non valides',
    errBadName: 'Nom de fichier non valide',
    errMissing: 'Fichier introuvable',
    errExists: 'Un fichier du même nom existe déjà',
    errRenameFailed: 'Échec du renommage',
    errNewTabFailed: 'Impossible de créer le nouveau document',
    errUnsupportedExt: 'les fichiers .{ext} ne sont pas pris en charge',
    copySuffix: 'copie',
    menuHelp: 'Aide',
    thirdPartyNotices: 'Mentions relatives aux logiciels tiers',
    menuExportDocx: 'Exporter en Word…',
    btnCancel: 'Annuler',
    pdfDocxFailedMsg: "Échec de l'export en Word",
    pdfDocxBusyMsg: "Un export en Word est déjà en cours. Veuillez attendre qu'il se termine.",
    menuExportDocxLocal: 'Exporter en Word (local)…',
    menuExportPptx: 'Exporter en PowerPoint…',
    pdfPptxFailedMsg: "Échec de l'exportation en PowerPoint",
    pdfPptxBusyMsg: "Une exportation est déjà en cours. Veuillez attendre qu'elle se termine.",
    pdfPptxLocalScannedDetail:
      "Chaque page a été exportée sous forme d'image ; le texte des diapositives n'est pas modifiable.",
    menuExportXlsx: 'Exporter en Excel…',
    pdfXlsxFailedMsg: "Échec de l'exportation en Excel",
    pdfXlsxBusyMsg: "Une exportation est déjà en cours. Veuillez attendre qu'elle se termine.",
    pdfXlsxLocalScannedDetail:
      "Les pages numérisées ne peuvent pas être converties en cellules ; la feuille de chaque page contient une ligne d'avertissement.",
    pdfXlsxLocalSkippedMsg: "Certaines pages n'ont pas été converties en cellules",
    pdfXlsxLocalSkippedDetail:
      "Les pages {pages} n'ont pas pu être converties en cellules ; leurs feuilles contiennent une ligne d'avertissement.",
    pdfDocxLocalScannedMsg: 'Document numérisé détecté',
    pdfDocxLocalScannedDetail:
      "La conversion locale a exporté les pages sous forme d'images pour préserver leur apparence. Pour un texte modifiable, utilisez la conversion cloud (avec OCR).",
    pdfDocxLocalDegradedMsg: 'Certaines pages ont été exportées en images',
    pdfDocxLocalDegradedDetail:
      "Les pages {pages} n'ont pas pu être reconstruites de manière fiable et ont été exportées en images pleine page.",
    pdfDocxLocalOcrMsg: 'Pages numérisées converties en texte modifiable',
    pdfDocxLocalOcrDetail:
      'Les pages {pages} étaient des numérisations ; leur texte a été restitué par OCR local. Veuillez relire le résultat.',
    pdfDocxLocalEncryptedDetail:
      "Ce PDF est chiffré et n'a pas pu être ouvert sans le mot de passe correct.",
    pdfDocxLocalUnsupportedEncDetail:
      'Ce PDF utilise un chiffrement par certificat ou un chiffrement non pris en charge et ne peut pas être converti localement. Essayez la conversion cloud.',
    pdfPwdTitle: 'Saisir le mot de passe',
    pdfPwdPrompt: "Ce PDF est chiffré. Saisissez le mot de passe pour l'ouvrir :",
    pdfPwdRetryPrompt: 'Mot de passe incorrect. Veuillez réessayer.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Vérification du mot de passe…',
    pdfPwdLabel: 'Mot de passe',
    pdfPwdPlaceholder: 'Saisissez le mot de passe d’ouverture',
    pdfPwdShow: 'Afficher le mot de passe',
    pdfPwdHide: 'Masquer le mot de passe',
    pdfDocxLocalCorruptDetail:
      "Le fichier est endommagé ou n'est pas un PDF valide et ne peut pas être converti.",
    dlgPickSaveDir: "Choisir l'emplacement d'enregistrement par défaut",
    errSaveDirUnusable:
      "Le dossier sélectionné n'est pas accessible en écriture et ne peut pas servir d'emplacement d'enregistrement par défaut",
  },
  de: {
    menuFile: 'Datei',
    menuSectionNew: 'Neu',
    untitledDeck: 'Unbenannte Leinwand',
    menuNewSlide: 'Neue Leinwand',
    menuExportPdf: 'Als PDF exportieren…',
    menuOpenInDocs: 'In Docs umwandeln und öffnen',
    menuPrint: 'Drucken…',
    menuOpen: 'Öffnen…',
    menuSave: 'Speichern',
    menuSaveAs: 'Speichern unter…',
    menuClose: 'Schließen',
    menuEdit: 'Bearbeiten',
    menuWindow: 'Fenster',
    menuHome: 'Startseite',
    backToHome: 'Zurück zur Startseite',
    dlgOpenTitle: 'Datei öffnen',
    filterSupported: 'Unterstützte Dateien',
    errBadArgs: 'Ungültige Argumente',
    errBadName: 'Ungültiger Dateiname',
    errMissing: 'Datei nicht gefunden',
    errExists: 'Eine Datei mit diesem Namen existiert bereits',
    errRenameFailed: 'Umbenennen fehlgeschlagen',
    errNewTabFailed: 'Neues Dokument konnte nicht erstellt werden',
    errUnsupportedExt: '.{ext}-Dateien werden nicht unterstützt',
    copySuffix: 'Kopie',
    menuHelp: 'Hilfe',
    thirdPartyNotices: 'Hinweise zu Drittanbietersoftware',
    menuExportDocx: 'Als Word exportieren…',
    btnCancel: 'Abbrechen',
    pdfDocxFailedMsg: 'Word-Export fehlgeschlagen',
    pdfDocxBusyMsg: 'Ein Word-Export läuft bereits. Bitte warten Sie, bis er abgeschlossen ist.',
    menuExportDocxLocal: 'Als Word exportieren (lokal)…',
    menuExportPptx: 'Als PowerPoint exportieren…',
    pdfPptxFailedMsg: 'Export als PowerPoint fehlgeschlagen',
    pdfPptxBusyMsg: 'Ein Export läuft bereits. Bitte warten Sie, bis er abgeschlossen ist.',
    pdfPptxLocalScannedDetail:
      'Jede Seite wurde als Bild exportiert; der Text auf den Folien ist nicht bearbeitbar.',
    menuExportXlsx: 'Als Excel exportieren…',
    pdfXlsxFailedMsg: 'Export als Excel fehlgeschlagen',
    pdfXlsxBusyMsg: 'Ein Export läuft bereits. Bitte warten Sie, bis er abgeschlossen ist.',
    pdfXlsxLocalScannedDetail:
      'Gescannte Seiten können nicht in Zellen umgewandelt werden; das Arbeitsblatt jeder Seite enthält stattdessen eine Hinweiszeile.',
    pdfXlsxLocalSkippedMsg: 'Einige Seiten wurden nicht in Zellen umgewandelt',
    pdfXlsxLocalSkippedDetail:
      'Die Seiten {pages} konnten nicht in Zellen umgewandelt werden; ihre Arbeitsblätter enthalten stattdessen eine Hinweiszeile.',
    pdfDocxLocalScannedMsg: 'Gescanntes Dokument erkannt',
    pdfDocxLocalScannedDetail:
      'Die lokale Konvertierung hat die Seiten als Bilder exportiert, um ihr Aussehen zu erhalten. Für bearbeitbaren Text nutzen Sie die Cloud-Konvertierung (mit OCR).',
    pdfDocxLocalDegradedMsg: 'Einige Seiten wurden als Bilder exportiert',
    pdfDocxLocalDegradedDetail:
      'Seite(n) {pages} konnten nicht zuverlässig rekonstruiert werden und wurden als ganzseitige Bilder exportiert.',
    pdfDocxLocalOcrMsg: 'Gescannte Seiten in bearbeitbaren Text umgewandelt',
    pdfDocxLocalOcrDetail:
      'Seite(n) {pages} waren Scans; der Text wurde per lokaler OCR wiederhergestellt. Bitte prüfen Sie das Ergebnis.',
    pdfDocxLocalEncryptedDetail:
      'Diese PDF ist verschlüsselt und konnte ohne das richtige Passwort nicht geöffnet werden.',
    pdfDocxLocalUnsupportedEncDetail:
      'Diese PDF verwendet eine zertifikatsbasierte oder nicht unterstützte Verschlüsselung und kann nicht lokal konvertiert werden. Versuchen Sie die Cloud-Konvertierung.',
    pdfPwdTitle: 'Passwort eingeben',
    pdfPwdPrompt: 'Diese PDF ist verschlüsselt. Geben Sie das Passwort zum Öffnen ein:',
    pdfPwdRetryPrompt: 'Falsches Passwort. Bitte versuchen Sie es erneut.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Passwort wird überprüft…',
    pdfPwdLabel: 'Passwort',
    pdfPwdPlaceholder: 'Passwort zum Öffnen eingeben',
    pdfPwdShow: 'Passwort anzeigen',
    pdfPwdHide: 'Passwort ausblenden',
    pdfDocxLocalCorruptDetail:
      'Die Datei ist beschädigt oder keine gültige PDF und kann nicht konvertiert werden.',
    dlgPickSaveDir: 'Standard-Speicherort auswählen',
    errSaveDirUnusable:
      'Der ausgewählte Ordner ist nicht beschreibbar und kann nicht als Standard-Speicherort verwendet werden',
  },
  es: {
    menuFile: 'Archivo',
    menuSectionNew: 'Nuevo',
    untitledDeck: 'Lienzo sin título',
    menuNewSlide: 'Nuevo lienzo',
    menuExportPdf: 'Exportar como PDF…',
    menuOpenInDocs: 'Convertir y abrir en Docs',
    menuPrint: 'Imprimir…',
    menuOpen: 'Abrir…',
    menuSave: 'Guardar',
    menuSaveAs: 'Guardar como…',
    menuClose: 'Cerrar',
    menuEdit: 'Edición',
    menuWindow: 'Ventana',
    menuHome: 'Inicio',
    backToHome: 'Volver al inicio',
    dlgOpenTitle: 'Abrir archivo',
    filterSupported: 'Archivos compatibles',
    errBadArgs: 'Argumentos no válidos',
    errBadName: 'Nombre de archivo no válido',
    errMissing: 'Archivo no encontrado',
    errExists: 'Ya existe un archivo con ese nombre',
    errRenameFailed: 'No se pudo cambiar el nombre',
    errNewTabFailed: 'No se pudo crear el nuevo documento',
    errUnsupportedExt: 'los archivos .{ext} no son compatibles',
    copySuffix: 'copia',
    menuHelp: 'Ayuda',
    thirdPartyNotices: 'Avisos de software de terceros',
    menuExportDocx: 'Exportar como Word…',
    btnCancel: 'Cancelar',
    pdfDocxFailedMsg: 'Error al exportar como Word',
    pdfDocxBusyMsg: 'Ya hay una exportación a Word en curso. Espera a que termine.',
    menuExportDocxLocal: 'Exportar como Word (local)…',
    menuExportPptx: 'Exportar como PowerPoint…',
    pdfPptxFailedMsg: 'Error al exportar como PowerPoint',
    pdfPptxBusyMsg: 'Ya hay una exportación en curso. Espere a que termine.',
    pdfPptxLocalScannedDetail:
      'Cada página se exportó como imagen; el texto de las diapositivas no es editable.',
    menuExportXlsx: 'Exportar como Excel…',
    pdfXlsxFailedMsg: 'Error al exportar como Excel',
    pdfXlsxBusyMsg: 'Ya hay una exportación en curso. Espere a que termine.',
    pdfXlsxLocalScannedDetail:
      'Las páginas escaneadas no se pueden convertir en celdas; la hoja de cada página incluye una fila de aviso.',
    pdfXlsxLocalSkippedMsg: 'Algunas páginas no se convirtieron en celdas',
    pdfXlsxLocalSkippedDetail:
      'Las páginas {pages} no se pudieron convertir en celdas; sus hojas incluyen una fila de aviso.',
    pdfDocxLocalScannedMsg: 'Documento escaneado detectado',
    pdfDocxLocalScannedDetail:
      'La conversión local exportó las páginas como imágenes para conservar su aspecto. Para texto editable, usa la conversión en la nube (con OCR).',
    pdfDocxLocalDegradedMsg: 'Algunas páginas se exportaron como imágenes',
    pdfDocxLocalDegradedDetail:
      'Las páginas {pages} no se pudieron reconstruir de forma fiable y se exportaron como imágenes de página completa.',
    pdfDocxLocalOcrMsg: 'Páginas escaneadas convertidas en texto editable',
    pdfDocxLocalOcrDetail:
      'Las páginas {pages} eran escaneos; su texto se recuperó con OCR local. Revise el resultado.',
    pdfDocxLocalEncryptedDetail:
      'Este PDF está cifrado y no se pudo abrir sin la contraseña correcta.',
    pdfDocxLocalUnsupportedEncDetail:
      'Este PDF usa cifrado basado en certificados u otro cifrado no compatible y no se puede convertir localmente. Prueba la conversión en la nube.',
    pdfPwdTitle: 'Introducir contraseña',
    pdfPwdPrompt: 'Este PDF está cifrado. Introduzca la contraseña para abrirlo:',
    pdfPwdRetryPrompt: 'Contraseña incorrecta. Inténtelo de nuevo.',
    pdfPwdOk: 'Aceptar',
    pdfPwdVerifying: 'Verificando la contraseña…',
    pdfPwdLabel: 'Contraseña',
    pdfPwdPlaceholder: 'Escriba la contraseña de apertura',
    pdfPwdShow: 'Mostrar contraseña',
    pdfPwdHide: 'Ocultar contraseña',
    pdfDocxLocalCorruptDetail:
      'El archivo está dañado o no es un PDF válido y no se puede convertir.',
    dlgPickSaveDir: 'Elegir ubicación de guardado predeterminada',
    errSaveDirUnusable:
      'La carpeta seleccionada no admite escritura y no puede usarse como ubicación de guardado predeterminada',
  },
  th: {
    menuFile: 'ไฟล์',
    menuSectionNew: 'สร้างใหม่',
    untitledDeck: 'ผืนงานไม่มีชื่อ',
    menuNewSlide: 'ผืนงานใหม่',
    menuExportPdf: 'ส่งออกเป็น PDF…',
    menuOpenInDocs: 'แปลงและเปิดใน Docs',
    menuPrint: 'พิมพ์…',
    menuOpen: 'เปิด…',
    menuSave: 'บันทึก',
    menuSaveAs: 'บันทึกเป็น…',
    menuClose: 'ปิด',
    menuEdit: 'แก้ไข',
    menuWindow: 'หน้าต่าง',
    menuHome: 'หน้าแรก',
    backToHome: 'กลับไปหน้าแรก',
    dlgOpenTitle: 'เปิดไฟล์',
    filterSupported: 'ไฟล์ที่รองรับ',
    errBadArgs: 'อาร์กิวเมนต์ไม่ถูกต้อง',
    errBadName: 'ชื่อไฟล์ไม่ถูกต้อง',
    errMissing: 'ไม่พบไฟล์',
    errExists: 'มีไฟล์ชื่อเดียวกันอยู่แล้ว',
    errRenameFailed: 'เปลี่ยนชื่อไม่สำเร็จ',
    errNewTabFailed: 'สร้างเอกสารใหม่ไม่สำเร็จ',
    errUnsupportedExt: 'ไม่รองรับไฟล์ .{ext}',
    copySuffix: 'สำเนา',
    menuHelp: 'วิธีใช้',
    thirdPartyNotices: 'ประกาศเกี่ยวกับซอฟต์แวร์ของบุคคลที่สาม',
    menuExportDocx: 'ส่งออกเป็น Word…',
    btnCancel: 'ยกเลิก',
    pdfDocxFailedMsg: 'ส่งออกเป็น Word ไม่สำเร็จ',
    pdfDocxBusyMsg: 'กำลังส่งออกเป็น Word อยู่ โปรดรอให้เสร็จสิ้นก่อน',
    menuExportDocxLocal: 'ส่งออกเป็น Word (แปลงในเครื่อง)…',
    menuExportPptx: 'ส่งออกเป็น PowerPoint…',
    pdfPptxFailedMsg: 'การส่งออกเป็น PowerPoint ล้มเหลว',
    pdfPptxBusyMsg: 'กำลังแปลงอยู่ โปรดรอให้การส่งออกปัจจุบันเสร็จสิ้น',
    pdfPptxLocalScannedDetail: 'แต่ละหน้าถูกส่งออกเป็นรูปภาพ ข้อความในสไลด์จึงแก้ไขไม่ได้',
    menuExportXlsx: 'ส่งออกเป็น Excel…',
    pdfXlsxFailedMsg: 'การส่งออกเป็น Excel ล้มเหลว',
    pdfXlsxBusyMsg: 'กำลังแปลงอยู่ โปรดรอให้การส่งออกปัจจุบันเสร็จสิ้น',
    pdfXlsxLocalScannedDetail:
      'หน้าที่สแกนไม่สามารถแปลงเป็นเซลล์ได้ เวิร์กชีตของแต่ละหน้าจึงมีแถวแจ้งเตือนแทน',
    pdfXlsxLocalSkippedMsg: 'บางหน้าไม่ได้ถูกแปลงเป็นเซลล์',
    pdfXlsxLocalSkippedDetail:
      'หน้า {pages} ไม่สามารถแปลงเป็นเซลล์ได้ เวิร์กชีตของหน้าดังกล่าวมีแถวแจ้งเตือนแทน',
    pdfDocxLocalScannedMsg: 'ตรวจพบเอกสารสแกน',
    pdfDocxLocalScannedDetail:
      'การแปลงในเครื่องได้ส่งออกแต่ละหน้าเป็นรูปภาพเพื่อคงรูปลักษณ์เดิม หากต้องการข้อความที่แก้ไขได้ โปรดใช้การแปลงบนคลาวด์ (รองรับ OCR)',
    pdfDocxLocalDegradedMsg: 'บางหน้าถูกส่งออกเป็นรูปภาพ',
    pdfDocxLocalDegradedDetail:
      'หน้า {pages} ไม่สามารถสร้างเลย์เอาต์ใหม่ได้อย่างน่าเชื่อถือ จึงส่งออกเป็นรูปภาพทั้งหน้า',
    pdfDocxLocalOcrMsg: 'แปลงหน้าสแกนเป็นข้อความที่แก้ไขได้แล้ว',
    pdfDocxLocalOcrDetail:
      'หน้า {pages} เป็นภาพสแกน ระบบกู้คืนข้อความด้วย OCR ในเครื่องแล้ว โปรดตรวจทานผลลัพธ์',
    pdfDocxLocalEncryptedDetail: 'PDF นี้ถูกเข้ารหัสและไม่สามารถเปิดได้โดยไม่มีรหัสผ่านที่ถูกต้อง',
    pdfDocxLocalUnsupportedEncDetail:
      'PDF นี้ใช้การเข้ารหัสแบบใบรับรองหรือการเข้ารหัสที่ไม่รองรับ จึงไม่สามารถแปลงในเครื่องได้ ลองใช้การแปลงบนคลาวด์แทน',
    pdfPwdTitle: 'ป้อนรหัสผ่าน',
    pdfPwdPrompt: 'PDF นี้ถูกเข้ารหัส โปรดป้อนรหัสผ่านเพื่อเปิด:',
    pdfPwdRetryPrompt: 'รหัสผ่านไม่ถูกต้อง โปรดลองอีกครั้ง',
    pdfPwdOk: 'ตกลง',
    pdfPwdVerifying: 'กำลังตรวจสอบรหัสผ่าน…',
    pdfPwdLabel: 'รหัสผ่าน',
    pdfPwdPlaceholder: 'ป้อนรหัสผ่านเพื่อเปิด',
    pdfPwdShow: 'แสดงรหัสผ่าน',
    pdfPwdHide: 'ซ่อนรหัสผ่าน',
    pdfDocxLocalCorruptDetail: 'ไฟล์เสียหายหรือไม่ใช่ PDF ที่ถูกต้อง จึงไม่สามารถแปลงได้',
    dlgPickSaveDir: 'เลือกตำแหน่งบันทึกเริ่มต้น',
    errSaveDirUnusable: 'โฟลเดอร์ที่เลือกไม่สามารถเขียนได้ จึงใช้เป็นตำแหน่งบันทึกเริ่มต้นไม่ได้',
  },
  id: {
    menuFile: 'File',
    menuSectionNew: 'Baru',
    untitledDeck: 'Kanvas tanpa judul',
    menuNewSlide: 'Kanvas baru',
    menuExportPdf: 'Ekspor sebagai PDF…',
    menuOpenInDocs: 'Konversi dan buka di Docs',
    menuPrint: 'Cetak…',
    menuOpen: 'Buka…',
    menuSave: 'Simpan',
    menuSaveAs: 'Simpan Sebagai…',
    menuClose: 'Tutup',
    menuEdit: 'Edit',
    menuWindow: 'Jendela',
    menuHome: 'Beranda',
    backToHome: 'Kembali ke Beranda',
    dlgOpenTitle: 'Buka File',
    filterSupported: 'File yang Didukung',
    errBadArgs: 'Argumen tidak valid',
    errBadName: 'Nama file tidak valid',
    errMissing: 'File tidak ditemukan',
    errExists: 'File dengan nama tersebut sudah ada',
    errRenameFailed: 'Gagal mengganti nama',
    errNewTabFailed: 'Gagal membuat dokumen baru',
    errUnsupportedExt: 'file .{ext} tidak didukung',
    copySuffix: 'salinan',
    menuHelp: 'Bantuan',
    thirdPartyNotices: 'Pemberitahuan Perangkat Lunak Pihak Ketiga',
    menuExportDocx: 'Ekspor sebagai Word…',
    btnCancel: 'Batal',
    pdfDocxFailedMsg: 'Gagal mengekspor sebagai Word',
    pdfDocxBusyMsg: 'Ekspor ke Word sedang berlangsung. Harap tunggu hingga selesai.',
    menuExportDocxLocal: 'Ekspor sebagai Word (lokal)…',
    menuExportPptx: 'Ekspor sebagai PowerPoint…',
    pdfPptxFailedMsg: 'Gagal mengekspor sebagai PowerPoint',
    pdfPptxBusyMsg: 'Ekspor sedang berlangsung. Harap tunggu hingga selesai.',
    pdfPptxLocalScannedDetail:
      'Setiap halaman diekspor sebagai gambar; teks pada slide tidak dapat diedit.',
    menuExportXlsx: 'Ekspor sebagai Excel…',
    pdfXlsxFailedMsg: 'Gagal mengekspor sebagai Excel',
    pdfXlsxBusyMsg: 'Ekspor sedang berlangsung. Harap tunggu hingga selesai.',
    pdfXlsxLocalScannedDetail:
      'Halaman hasil pindaian tidak dapat diubah menjadi sel; lembar kerja setiap halaman berisi baris pemberitahuan.',
    pdfXlsxLocalSkippedMsg: 'Beberapa halaman tidak diubah menjadi sel',
    pdfXlsxLocalSkippedDetail:
      'Halaman {pages} tidak dapat diubah menjadi sel; lembar kerjanya berisi baris pemberitahuan.',
    pdfDocxLocalScannedMsg: 'Dokumen hasil pindaian terdeteksi',
    pdfDocxLocalScannedDetail:
      'Konversi lokal mengekspor halaman sebagai gambar untuk mempertahankan tampilannya. Untuk teks yang dapat diedit, gunakan konversi cloud (dengan OCR).',
    pdfDocxLocalDegradedMsg: 'Beberapa halaman diekspor sebagai gambar',
    pdfDocxLocalDegradedDetail:
      'Halaman {pages} tidak dapat direkonstruksi dengan andal dan diekspor sebagai gambar satu halaman penuh.',
    pdfDocxLocalOcrMsg: 'Halaman pindaian diubah menjadi teks yang dapat diedit',
    pdfDocxLocalOcrDetail:
      'Halaman {pages} adalah hasil pindaian; teksnya dipulihkan dengan OCR lokal. Harap periksa hasilnya.',
    pdfDocxLocalEncryptedDetail:
      'PDF ini terenkripsi dan tidak dapat dibuka tanpa kata sandi yang benar.',
    pdfDocxLocalUnsupportedEncDetail:
      'PDF ini menggunakan enkripsi berbasis sertifikat atau enkripsi yang tidak didukung dan tidak dapat dikonversi secara lokal. Coba konversi cloud.',
    pdfPwdTitle: 'Masukkan Kata Sandi',
    pdfPwdPrompt: 'PDF ini terenkripsi. Masukkan kata sandi untuk membukanya:',
    pdfPwdRetryPrompt: 'Kata sandi salah. Silakan coba lagi.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Memverifikasi kata sandi…',
    pdfPwdLabel: 'Kata sandi',
    pdfPwdPlaceholder: 'Masukkan kata sandi buka',
    pdfPwdShow: 'Tampilkan kata sandi',
    pdfPwdHide: 'Sembunyikan kata sandi',
    pdfDocxLocalCorruptDetail:
      'File rusak atau bukan PDF yang valid sehingga tidak dapat dikonversi.',
    dlgPickSaveDir: 'Pilih Lokasi Penyimpanan Default',
    errSaveDirUnusable:
      'Folder yang dipilih tidak dapat ditulis dan tidak bisa digunakan sebagai lokasi penyimpanan default',
  },
  ru: {
    menuFile: 'Файл',
    menuSectionNew: 'Создать',
    untitledDeck: 'Холст без названия',
    menuNewSlide: 'Новый холст',
    menuExportPdf: 'Экспортировать в PDF…',
    menuOpenInDocs: 'Преобразовать и открыть в Docs',
    menuPrint: 'Печать…',
    menuOpen: 'Открыть…',
    menuSave: 'Сохранить',
    menuSaveAs: 'Сохранить как…',
    menuClose: 'Закрыть',
    menuEdit: 'Правка',
    menuWindow: 'Окно',
    menuHome: 'Главная',
    backToHome: 'Вернуться на главную',
    dlgOpenTitle: 'Открытие файла',
    filterSupported: 'Поддерживаемые файлы',
    errBadArgs: 'Недопустимые аргументы',
    errBadName: 'Недопустимое имя файла',
    errMissing: 'Файл не найден',
    errExists: 'Файл с таким именем уже существует',
    errRenameFailed: 'Не удалось переименовать',
    errNewTabFailed: 'Не удалось создать новый документ',
    errUnsupportedExt: 'файлы .{ext} не поддерживаются',
    copySuffix: 'копия',
    menuHelp: 'Справка',
    thirdPartyNotices: 'Уведомления о стороннем ПО',
    menuExportDocx: 'Экспортировать в Word…',
    btnCancel: 'Отмена',
    pdfDocxFailedMsg: 'Не удалось экспортировать в Word',
    pdfDocxBusyMsg: 'Экспорт в Word уже выполняется. Дождитесь его завершения.',
    menuExportDocxLocal: 'Экспортировать в Word (локально)…',
    menuExportPptx: 'Экспортировать в PowerPoint…',
    pdfPptxFailedMsg: 'Не удалось экспортировать в PowerPoint',
    pdfPptxBusyMsg: 'Экспорт уже выполняется. Дождитесь его завершения.',
    pdfPptxLocalScannedDetail:
      'Каждая страница экспортирована как изображение; текст на слайдах нельзя редактировать.',
    menuExportXlsx: 'Экспортировать в Excel…',
    pdfXlsxFailedMsg: 'Не удалось экспортировать в Excel',
    pdfXlsxBusyMsg: 'Экспорт уже выполняется. Дождитесь его завершения.',
    pdfXlsxLocalScannedDetail:
      'Отсканированные страницы нельзя преобразовать в ячейки; на листе каждой страницы добавлена строка с уведомлением.',
    pdfXlsxLocalSkippedMsg: 'Некоторые страницы не были преобразованы в ячейки',
    pdfXlsxLocalSkippedDetail:
      'Страницы {pages} не удалось преобразовать в ячейки; на их листах добавлена строка с уведомлением.',
    pdfDocxLocalScannedMsg: 'Обнаружен отсканированный документ',
    pdfDocxLocalScannedDetail:
      'Локальное преобразование экспортировало страницы как изображения, чтобы сохранить их вид. Для редактируемого текста используйте облачное преобразование (с OCR).',
    pdfDocxLocalDegradedMsg: 'Некоторые страницы экспортированы как изображения',
    pdfDocxLocalDegradedDetail:
      'Страницы {pages} не удалось надёжно реконструировать; они экспортированы как полностраничные изображения.',
    pdfDocxLocalOcrMsg: 'Отсканированные страницы преобразованы в редактируемый текст',
    pdfDocxLocalOcrDetail:
      'Страницы {pages} были сканами; текст восстановлен локальным OCR. Проверьте результат.',
    pdfDocxLocalEncryptedDetail:
      'Этот PDF зашифрован, и его не удалось открыть без правильного пароля.',
    pdfDocxLocalUnsupportedEncDetail:
      'Этот PDF использует шифрование на основе сертификата или другое неподдерживаемое шифрование, локальное преобразование невозможно. Попробуйте облачное преобразование.',
    pdfPwdTitle: 'Введите пароль',
    pdfPwdPrompt: 'Этот PDF зашифрован. Введите пароль, чтобы открыть его:',
    pdfPwdRetryPrompt: 'Неверный пароль. Попробуйте ещё раз.',
    pdfPwdOk: 'ОК',
    pdfPwdVerifying: 'Проверка пароля…',
    pdfPwdLabel: 'Пароль',
    pdfPwdPlaceholder: 'Введите пароль для открытия',
    pdfPwdShow: 'Показать пароль',
    pdfPwdHide: 'Скрыть пароль',
    pdfDocxLocalCorruptDetail:
      'Файл повреждён или не является корректным PDF, преобразование невозможно.',
    dlgPickSaveDir: 'Выбрать папку сохранения по умолчанию',
    errSaveDirUnusable:
      'Выбранная папка недоступна для записи и не может использоваться как папка сохранения по умолчанию',
  },
  ar: {
    menuFile: 'ملف',
    menuSectionNew: 'جديد',
    untitledDeck: 'لوحة رسم بلا عنوان',
    menuNewSlide: 'لوحة رسم جديدة',
    menuExportPdf: 'تصدير بتنسيق PDF…',
    menuOpenInDocs: 'التحويل والفتح في Docs',
    menuPrint: 'طباعة…',
    menuOpen: 'فتح…',
    menuSave: 'حفظ',
    menuSaveAs: 'حفظ باسم…',
    menuClose: 'إغلاق',
    menuEdit: 'تحرير',
    menuWindow: 'نافذة',
    menuHome: 'الصفحة الرئيسية',
    backToHome: 'العودة إلى الصفحة الرئيسية',
    dlgOpenTitle: 'فتح ملف',
    filterSupported: 'الملفات المدعومة',
    errBadArgs: 'وسيطات غير صالحة',
    errBadName: 'اسم ملف غير صالح',
    errMissing: 'الملف غير موجود',
    errExists: 'يوجد ملف بالاسم نفسه بالفعل',
    errRenameFailed: 'فشلت إعادة التسمية',
    errNewTabFailed: 'تعذّر إنشاء المستند الجديد',
    errUnsupportedExt: 'ملفات .{ext} غير مدعومة',
    copySuffix: 'نسخة',
    menuHelp: 'تعليمات',
    thirdPartyNotices: 'إشعارات برامج الجهات الخارجية',
    menuExportDocx: 'تصدير كملف Word…',
    btnCancel: 'إلغاء',
    pdfDocxFailedMsg: 'فشل التصدير كملف Word',
    pdfDocxBusyMsg: 'يجري حاليًا تصدير إلى Word. يُرجى الانتظار حتى يكتمل.',
    menuExportDocxLocal: 'تصدير كملف Word (تحويل محلي)…',
    menuExportPptx: 'تصدير كملف PowerPoint…',
    pdfPptxFailedMsg: 'فشل التصدير كملف PowerPoint',
    pdfPptxBusyMsg: 'هناك عملية تصدير قيد التنفيذ. يرجى الانتظار حتى تكتمل.',
    pdfPptxLocalScannedDetail: 'تم تصدير كل صفحة كصورة؛ النص في الشرائح غير قابل للتحرير.',
    menuExportXlsx: 'تصدير كملف Excel…',
    pdfXlsxFailedMsg: 'فشل التصدير كملف Excel',
    pdfXlsxBusyMsg: 'هناك عملية تصدير قيد التنفيذ. يرجى الانتظار حتى تكتمل.',
    pdfXlsxLocalScannedDetail:
      'لا يمكن تحويل الصفحات الممسوحة ضوئيًا إلى خلايا؛ تحتوي ورقة كل صفحة على صف تنبيه بدلاً من ذلك.',
    pdfXlsxLocalSkippedMsg: 'لم يتم تحويل بعض الصفحات إلى خلايا',
    pdfXlsxLocalSkippedDetail:
      'تعذر تحويل الصفحات {pages} إلى خلايا؛ تحتوي أوراقها على صف تنبيه بدلاً من ذلك.',
    pdfDocxLocalScannedMsg: 'تم اكتشاف مستند ممسوح ضوئيًا',
    pdfDocxLocalScannedDetail:
      'قام التحويل المحلي بتصدير الصفحات كصور للحفاظ على مظهرها. للحصول على نص قابل للتحرير، استخدم التحويل السحابي (مع OCR).',
    pdfDocxLocalDegradedMsg: 'تم تصدير بعض الصفحات كصور',
    pdfDocxLocalDegradedDetail:
      'تعذّرت إعادة بناء الصفحات {pages} بشكل موثوق، وتم تصديرها كصور لكامل الصفحة.',
    pdfDocxLocalOcrMsg: 'تم تحويل الصفحات الممسوحة ضوئيًا إلى نص قابل للتحرير',
    pdfDocxLocalOcrDetail:
      'الصفحات {pages} كانت صورًا ممسوحة؛ تم استرداد النص عبر OCR المحلي. يُرجى مراجعة النتيجة.',
    pdfDocxLocalEncryptedDetail: 'هذا الملف PDF مشفّر وتعذّر فتحه دون كلمة المرور الصحيحة.',
    pdfDocxLocalUnsupportedEncDetail:
      'يستخدم ملف PDF هذا تشفيرًا قائمًا على الشهادات أو تشفيرًا غير مدعوم ولا يمكن تحويله محليًا. جرّب التحويل السحابي.',
    pdfPwdTitle: 'إدخال كلمة المرور',
    pdfPwdPrompt: 'هذا الملف PDF مشفّر. أدخل كلمة المرور لفتحه:',
    pdfPwdRetryPrompt: 'كلمة المرور غير صحيحة. حاول مرة أخرى.',
    pdfPwdOk: 'موافق',
    pdfPwdVerifying: 'جارٍ التحقق من كلمة المرور…',
    pdfPwdLabel: 'كلمة المرور',
    pdfPwdPlaceholder: 'أدخل كلمة مرور الفتح',
    pdfPwdShow: 'إظهار كلمة المرور',
    pdfPwdHide: 'إخفاء كلمة المرور',
    pdfDocxLocalCorruptDetail: 'الملف تالف أو ليس ملف PDF صالحًا ولا يمكن تحويله.',
    dlgPickSaveDir: 'اختيار موقع الحفظ الافتراضي',
    errSaveDirUnusable: 'المجلد المحدد غير قابل للكتابة ولا يمكن استخدامه كموقع حفظ افتراضي',
  },
  pt: {
    menuFile: 'Arquivo',
    menuSectionNew: 'Novo',
    untitledDeck: 'Tela sem título',
    menuNewSlide: 'Nova tela',
    menuExportPdf: 'Exportar como PDF…',
    menuOpenInDocs: 'Converter e abrir no Docs',
    menuPrint: 'Imprimir…',
    menuOpen: 'Abrir…',
    menuSave: 'Salvar',
    menuSaveAs: 'Salvar Como…',
    menuClose: 'Fechar',
    menuEdit: 'Editar',
    menuWindow: 'Janela',
    menuHome: 'Início',
    backToHome: 'Voltar ao início',
    dlgOpenTitle: 'Abrir arquivo',
    filterSupported: 'Arquivos compatíveis',
    errBadArgs: 'Argumentos inválidos',
    errBadName: 'Nome de arquivo inválido',
    errMissing: 'Arquivo não encontrado',
    errExists: 'Já existe um arquivo com esse nome',
    errRenameFailed: 'Falha ao renomear',
    errNewTabFailed: 'Falha ao criar o novo documento',
    errUnsupportedExt: 'arquivos .{ext} não são suportados',
    copySuffix: 'cópia',
    menuHelp: 'Ajuda',
    thirdPartyNotices: 'Avisos de software de terceiros',
    menuExportDocx: 'Exportar como Word…',
    btnCancel: 'Cancelar',
    pdfDocxFailedMsg: 'Falha ao exportar como Word',
    pdfDocxBusyMsg: 'Já há uma exportação para Word em andamento. Aguarde a conclusão.',
    menuExportDocxLocal: 'Exportar como Word (local)…',
    menuExportPptx: 'Exportar como PowerPoint…',
    pdfPptxFailedMsg: 'Falha ao exportar como PowerPoint',
    pdfPptxBusyMsg: 'Já há uma exportação em andamento. Aguarde a conclusão.',
    pdfPptxLocalScannedDetail:
      'Cada página foi exportada como imagem; o texto dos slides não é editável.',
    menuExportXlsx: 'Exportar como Excel…',
    pdfXlsxFailedMsg: 'Falha ao exportar como Excel',
    pdfXlsxBusyMsg: 'Já há uma exportação em andamento. Aguarde a conclusão.',
    pdfXlsxLocalScannedDetail:
      'Páginas digitalizadas não podem ser convertidas em células; a planilha de cada página contém uma linha de aviso.',
    pdfXlsxLocalSkippedMsg: 'Algumas páginas não foram convertidas em células',
    pdfXlsxLocalSkippedDetail:
      'As páginas {pages} não puderam ser convertidas em células; suas planilhas contêm uma linha de aviso.',
    pdfDocxLocalScannedMsg: 'Documento digitalizado detectado',
    pdfDocxLocalScannedDetail:
      'A conversão local exportou as páginas como imagens para preservar a aparência. Para texto editável, use a conversão na nuvem (com OCR).',
    pdfDocxLocalDegradedMsg: 'Algumas páginas foram exportadas como imagens',
    pdfDocxLocalDegradedDetail:
      'As páginas {pages} não puderam ser reconstruídas de forma confiável e foram exportadas como imagens de página inteira.',
    pdfDocxLocalOcrMsg: 'Páginas digitalizadas convertidas em texto editável',
    pdfDocxLocalOcrDetail:
      'As páginas {pages} eram digitalizações; o texto foi recuperado com OCR local. Revise o resultado.',
    pdfDocxLocalEncryptedDetail:
      'Este PDF está criptografado e não pôde ser aberto sem a senha correta.',
    pdfDocxLocalUnsupportedEncDetail:
      'Este PDF usa criptografia baseada em certificado ou outra criptografia sem suporte e não pode ser convertido localmente. Experimente a conversão na nuvem.',
    pdfPwdTitle: 'Digitar senha',
    pdfPwdPrompt: 'Este PDF está criptografado. Digite a senha para abri-lo:',
    pdfPwdRetryPrompt: 'Senha incorreta. Tente novamente.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Verificando a senha…',
    pdfPwdLabel: 'Senha',
    pdfPwdPlaceholder: 'Digite a senha de abertura',
    pdfPwdShow: 'Mostrar senha',
    pdfPwdHide: 'Ocultar senha',
    pdfDocxLocalCorruptDetail:
      'O arquivo está danificado ou não é um PDF válido e não pode ser convertido.',
    dlgPickSaveDir: 'Escolher local de salvamento padrão',
    errSaveDirUnusable:
      'A pasta selecionada não permite gravação e não pode ser usada como local de salvamento padrão',
  },
  it: {
    menuFile: 'File',
    menuSectionNew: 'Nuovo',
    untitledDeck: 'Tela senza titolo',
    menuNewSlide: 'Nuova tela',
    menuExportPdf: 'Esporta come PDF…',
    menuOpenInDocs: 'Converti e apri in Docs',
    menuPrint: 'Stampa…',
    menuOpen: 'Apri…',
    menuSave: 'Salva',
    menuSaveAs: 'Salva con nome…',
    menuClose: 'Chiudi',
    menuEdit: 'Modifica',
    menuWindow: 'Finestra',
    menuHome: 'Home',
    backToHome: 'Torna alla Home',
    dlgOpenTitle: 'Apri file',
    filterSupported: 'File supportati',
    errBadArgs: 'Argomenti non validi',
    errBadName: 'Nome file non valido',
    errMissing: 'File non trovato',
    errExists: 'Esiste già un file con questo nome',
    errRenameFailed: 'Impossibile rinominare',
    errNewTabFailed: 'Impossibile creare il nuovo documento',
    errUnsupportedExt: 'i file .{ext} non sono supportati',
    copySuffix: 'copia',
    menuHelp: 'Aiuto',
    thirdPartyNotices: 'Note sul software di terze parti',
    menuExportDocx: 'Esporta come Word…',
    btnCancel: 'Annulla',
    pdfDocxFailedMsg: 'Esportazione in Word non riuscita',
    pdfDocxBusyMsg: "Un'esportazione in Word è già in corso. Attendi il completamento.",
    menuExportDocxLocal: 'Esporta come Word (locale)…',
    menuExportPptx: 'Esporta come PowerPoint…',
    pdfPptxFailedMsg: 'Esportazione come PowerPoint non riuscita',
    pdfPptxBusyMsg: "Un'esportazione è già in corso. Attendere che finisca.",
    pdfPptxLocalScannedDetail:
      'Ogni pagina è stata esportata come immagine; il testo delle diapositive non è modificabile.',
    menuExportXlsx: 'Esporta come Excel…',
    pdfXlsxFailedMsg: 'Esportazione come Excel non riuscita',
    pdfXlsxBusyMsg: "Un'esportazione è già in corso. Attendere che finisca.",
    pdfXlsxLocalScannedDetail:
      'Le pagine scansionate non possono essere convertite in celle; il foglio di ogni pagina contiene una riga di avviso.',
    pdfXlsxLocalSkippedMsg: 'Alcune pagine non sono state convertite in celle',
    pdfXlsxLocalSkippedDetail:
      'Le pagine {pages} non hanno potuto essere convertite in celle; i loro fogli contengono una riga di avviso.',
    pdfDocxLocalScannedMsg: 'Rilevato documento scansionato',
    pdfDocxLocalScannedDetail:
      "La conversione locale ha esportato le pagine come immagini per preservarne l'aspetto. Per testo modificabile, usa la conversione cloud (con OCR).",
    pdfDocxLocalDegradedMsg: 'Alcune pagine sono state esportate come immagini',
    pdfDocxLocalDegradedDetail:
      'Non è stato possibile ricostruire in modo affidabile le pagine {pages}; sono state esportate come immagini a pagina intera.',
    pdfDocxLocalOcrMsg: 'Pagine scansionate convertite in testo modificabile',
    pdfDocxLocalOcrDetail:
      'Le pagine {pages} erano scansioni; il testo è stato recuperato con OCR locale. Si consiglia di rileggere il risultato.',
    pdfDocxLocalEncryptedDetail:
      'Questo PDF è crittografato e non è stato possibile aprirlo senza la password corretta.',
    pdfDocxLocalUnsupportedEncDetail:
      'Questo PDF usa una crittografia basata su certificati o comunque non supportata e non può essere convertito localmente. Prova la conversione cloud.',
    pdfPwdTitle: 'Inserisci password',
    pdfPwdPrompt: 'Questo PDF è crittografato. Inserisci la password per aprirlo:',
    pdfPwdRetryPrompt: 'Password errata. Riprova.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Verifica della password…',
    pdfPwdLabel: 'Password',
    pdfPwdPlaceholder: 'Inserisci la password di apertura',
    pdfPwdShow: 'Mostra password',
    pdfPwdHide: 'Nascondi password',
    pdfDocxLocalCorruptDetail:
      'Il file è danneggiato o non è un PDF valido e non può essere convertito.',
    dlgPickSaveDir: 'Scegli la posizione di salvataggio predefinita',
    errSaveDirUnusable:
      'La cartella selezionata non è scrivibile e non può essere usata come posizione di salvataggio predefinita',
  },
  pl: {
    menuFile: 'Plik',
    menuSectionNew: 'Nowy',
    untitledDeck: 'Płótno bez tytułu',
    menuNewSlide: 'Nowe płótno',
    menuExportPdf: 'Eksportuj jako PDF…',
    menuOpenInDocs: 'Konwertuj i otwórz w Docs',
    menuPrint: 'Drukuj…',
    menuOpen: 'Otwórz…',
    menuSave: 'Zapisz',
    menuSaveAs: 'Zapisz jako…',
    menuClose: 'Zamknij',
    menuEdit: 'Edycja',
    menuWindow: 'Okno',
    menuHome: 'Strona główna',
    backToHome: 'Wróć do strony głównej',
    dlgOpenTitle: 'Otwieranie pliku',
    filterSupported: 'Obsługiwane pliki',
    errBadArgs: 'Nieprawidłowe argumenty',
    errBadName: 'Nieprawidłowa nazwa pliku',
    errMissing: 'Nie znaleziono pliku',
    errExists: 'Plik o tej nazwie już istnieje',
    errRenameFailed: 'Nie udało się zmienić nazwy',
    errNewTabFailed: 'Nie udało się utworzyć nowego dokumentu',
    errUnsupportedExt: 'pliki .{ext} nie są obsługiwane',
    copySuffix: 'kopia',
    menuHelp: 'Pomoc',
    thirdPartyNotices: 'Informacje o oprogramowaniu innych firm',
    menuExportDocx: 'Eksportuj jako Word…',
    btnCancel: 'Anuluj',
    pdfDocxFailedMsg: 'Eksport do formatu Word nie powiódł się',
    pdfDocxBusyMsg: 'Eksport do formatu Word już trwa. Poczekaj na jego zakończenie.',
    menuExportDocxLocal: 'Eksportuj jako Word (lokalnie)…',
    menuExportPptx: 'Eksportuj jako PowerPoint…',
    pdfPptxFailedMsg: 'Eksport jako PowerPoint nie powiódł się',
    pdfPptxBusyMsg: 'Eksport już trwa. Poczekaj na jego zakończenie.',
    pdfPptxLocalScannedDetail:
      'Każda strona została wyeksportowana jako obraz; tekst na slajdach nie jest edytowalny.',
    menuExportXlsx: 'Eksportuj jako Excel…',
    pdfXlsxFailedMsg: 'Eksport jako Excel nie powiódł się',
    pdfXlsxBusyMsg: 'Eksport już trwa. Poczekaj na jego zakończenie.',
    pdfXlsxLocalScannedDetail:
      'Zeskanowanych stron nie można przekształcić w komórki; arkusz każdej strony zawiera wiersz z informacją.',
    pdfXlsxLocalSkippedMsg: 'Niektóre strony nie zostały przekształcone w komórki',
    pdfXlsxLocalSkippedDetail:
      'Stron {pages} nie udało się przekształcić w komórki; ich arkusze zawierają wiersz z informacją.',
    pdfDocxLocalScannedMsg: 'Wykryto zeskanowany dokument',
    pdfDocxLocalScannedDetail:
      'Konwersja lokalna wyeksportowała strony jako obrazy, aby zachować ich wygląd. Aby uzyskać edytowalny tekst, użyj konwersji w chmurze (z OCR).',
    pdfDocxLocalDegradedMsg: 'Niektóre strony wyeksportowano jako obrazy',
    pdfDocxLocalDegradedDetail:
      'Stron {pages} nie udało się wiarygodnie odtworzyć; wyeksportowano je jako obrazy całych stron.',
    pdfDocxLocalOcrMsg: 'Zeskanowane strony przekonwertowano na edytowalny tekst',
    pdfDocxLocalOcrDetail:
      'Strony {pages} były skanami; tekst odzyskano lokalnym OCR. Sprawdź wynik.',
    pdfDocxLocalEncryptedDetail:
      'Ten PDF jest zaszyfrowany i nie można go otworzyć bez prawidłowego hasła.',
    pdfDocxLocalUnsupportedEncDetail:
      'Ten PDF używa szyfrowania opartego na certyfikatach lub innego nieobsługiwanego szyfrowania i nie można go przekonwertować lokalnie. Wypróbuj konwersję w chmurze.',
    pdfPwdTitle: 'Wprowadź hasło',
    pdfPwdPrompt: 'Ten PDF jest zaszyfrowany. Wprowadź hasło, aby go otworzyć:',
    pdfPwdRetryPrompt: 'Nieprawidłowe hasło. Spróbuj ponownie.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Weryfikowanie hasła…',
    pdfPwdLabel: 'Hasło',
    pdfPwdPlaceholder: 'Wprowadź hasło otwarcia',
    pdfPwdShow: 'Pokaż hasło',
    pdfPwdHide: 'Ukryj hasło',
    pdfDocxLocalCorruptDetail:
      'Plik jest uszkodzony lub nie jest prawidłowym plikiem PDF i nie można go przekonwertować.',
    dlgPickSaveDir: 'Wybierz domyślną lokalizację zapisu',
    errSaveDirUnusable:
      'Wybrany folder nie pozwala na zapis i nie może być domyślną lokalizacją zapisu',
  },
  nl: {
    menuFile: 'Bestand',
    menuSectionNew: 'Nieuw',
    untitledDeck: 'Naamloos canvas',
    menuNewSlide: 'Nieuw canvas',
    menuExportPdf: 'Exporteren als PDF…',
    menuOpenInDocs: 'Converteren en openen in Docs',
    menuPrint: 'Afdrukken…',
    menuOpen: 'Openen…',
    menuSave: 'Opslaan',
    menuSaveAs: 'Opslaan als…',
    menuClose: 'Sluiten',
    menuEdit: 'Bewerken',
    menuWindow: 'Venster',
    menuHome: 'Start',
    backToHome: 'Terug naar start',
    dlgOpenTitle: 'Bestand openen',
    filterSupported: 'Ondersteunde bestanden',
    errBadArgs: 'Ongeldige argumenten',
    errBadName: 'Ongeldige bestandsnaam',
    errMissing: 'Bestand niet gevonden',
    errExists: 'Er bestaat al een bestand met die naam',
    errRenameFailed: 'Naam wijzigen mislukt',
    errNewTabFailed: 'Kan het nieuwe document niet maken',
    errUnsupportedExt: '.{ext}-bestanden worden niet ondersteund',
    copySuffix: 'kopie',
    menuHelp: 'Help',
    thirdPartyNotices: 'Kennisgevingen over software van derden',
    menuExportDocx: 'Exporteren als Word…',
    btnCancel: 'Annuleren',
    pdfDocxFailedMsg: 'Exporteren als Word mislukt',
    pdfDocxBusyMsg: 'Er is al een Word-export bezig. Wacht tot deze is voltooid.',
    menuExportDocxLocal: 'Exporteren als Word (lokaal)…',
    menuExportPptx: 'Exporteren als PowerPoint…',
    pdfPptxFailedMsg: 'Exporteren als PowerPoint mislukt',
    pdfPptxBusyMsg: 'Er is al een export bezig. Wacht tot deze is voltooid.',
    pdfPptxLocalScannedDetail:
      'Elke pagina is als afbeelding geëxporteerd; de tekst op de dia’s is niet bewerkbaar.',
    menuExportXlsx: 'Exporteren als Excel…',
    pdfXlsxFailedMsg: 'Exporteren als Excel mislukt',
    pdfXlsxBusyMsg: 'Er is al een export bezig. Wacht tot deze is voltooid.',
    pdfXlsxLocalScannedDetail:
      "Gescande pagina's kunnen niet naar cellen worden omgezet; het werkblad van elke pagina bevat een meldingsrij.",
    pdfXlsxLocalSkippedMsg: "Sommige pagina's zijn niet naar cellen omgezet",
    pdfXlsxLocalSkippedDetail:
      "Pagina's {pages} konden niet naar cellen worden omgezet; hun werkbladen bevatten een meldingsrij.",
    pdfDocxLocalScannedMsg: 'Gescand document gedetecteerd',
    pdfDocxLocalScannedDetail:
      "De lokale conversie heeft de pagina's als afbeeldingen geëxporteerd om hun uiterlijk te behouden. Gebruik voor bewerkbare tekst de cloudconversie (met OCR).",
    pdfDocxLocalDegradedMsg: "Sommige pagina's zijn als afbeeldingen geëxporteerd",
    pdfDocxLocalDegradedDetail:
      "Pagina's {pages} konden niet betrouwbaar worden gereconstrueerd en zijn als paginagrote afbeeldingen geëxporteerd.",
    pdfDocxLocalOcrMsg: 'Gescande pagina’s omgezet naar bewerkbare tekst',
    pdfDocxLocalOcrDetail:
      'Pagina(’s) {pages} waren scans; de tekst is hersteld met lokale OCR. Controleer het resultaat.',
    pdfDocxLocalEncryptedDetail:
      'Deze PDF is versleuteld en kon niet worden geopend zonder het juiste wachtwoord.',
    pdfDocxLocalUnsupportedEncDetail:
      'Deze PDF gebruikt certificaatgebaseerde of anderszins niet-ondersteunde versleuteling en kan niet lokaal worden geconverteerd. Probeer de cloudconversie.',
    pdfPwdTitle: 'Wachtwoord invoeren',
    pdfPwdPrompt: 'Deze PDF is versleuteld. Voer het wachtwoord in om te openen:',
    pdfPwdRetryPrompt: 'Onjuist wachtwoord. Probeer het opnieuw.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Wachtwoord controleren…',
    pdfPwdLabel: 'Wachtwoord',
    pdfPwdPlaceholder: 'Voer het openingswachtwoord in',
    pdfPwdShow: 'Wachtwoord tonen',
    pdfPwdHide: 'Wachtwoord verbergen',
    pdfDocxLocalCorruptDetail:
      'Het bestand is beschadigd of geen geldige PDF en kan niet worden geconverteerd.',
    dlgPickSaveDir: 'Standaard opslaglocatie kiezen',
    errSaveDirUnusable:
      'De geselecteerde map is niet beschrijfbaar en kan niet als standaard opslaglocatie worden gebruikt',
  },
  ms: {
    menuFile: 'Fail',
    menuSectionNew: 'Baharu',
    untitledDeck: 'Kanvas tanpa tajuk',
    menuNewSlide: 'kanvas baharu',
    menuExportPdf: 'Eksport sebagai PDF…',
    menuOpenInDocs: 'Tukar dan buka dalam Docs',
    menuPrint: 'Cetak…',
    menuOpen: 'Buka…',
    menuSave: 'Simpan',
    menuSaveAs: 'Simpan Sebagai…',
    menuClose: 'Tutup',
    menuEdit: 'Edit',
    menuWindow: 'Tetingkap',
    menuHome: 'Laman Utama',
    backToHome: 'Kembali ke Laman Utama',
    dlgOpenTitle: 'Buka Fail',
    filterSupported: 'Fail yang Disokong',
    errBadArgs: 'Argumen tidak sah',
    errBadName: 'Nama fail tidak sah',
    errMissing: 'Fail tidak ditemui',
    errExists: 'Fail dengan nama yang sama sudah wujud',
    errRenameFailed: 'Gagal menamakan semula',
    errNewTabFailed: 'Gagal mencipta dokumen baharu',
    errUnsupportedExt: 'fail .{ext} tidak disokong',
    copySuffix: 'salinan',
    menuHelp: 'Bantuan',
    thirdPartyNotices: 'Notis Perisian Pihak Ketiga',
    menuExportDocx: 'Eksport sebagai Word…',
    btnCancel: 'Batal',
    pdfDocxFailedMsg: 'Gagal mengeksport sebagai Word',
    pdfDocxBusyMsg: 'Eksport ke Word sedang dijalankan. Sila tunggu sehingga selesai.',
    menuExportDocxLocal: 'Eksport sebagai Word (setempat)…',
    menuExportPptx: 'Eksport sebagai PowerPoint…',
    pdfPptxFailedMsg: 'Eksport sebagai PowerPoint gagal',
    pdfPptxBusyMsg: 'Eksport sedang berjalan. Sila tunggu sehingga selesai.',
    pdfPptxLocalScannedDetail:
      'Setiap halaman dieksport sebagai imej; teks pada slaid tidak boleh diedit.',
    menuExportXlsx: 'Eksport sebagai Excel…',
    pdfXlsxFailedMsg: 'Eksport sebagai Excel gagal',
    pdfXlsxBusyMsg: 'Eksport sedang berjalan. Sila tunggu sehingga selesai.',
    pdfXlsxLocalScannedDetail:
      'Halaman imbasan tidak boleh ditukar kepada sel; helaian setiap halaman mengandungi baris makluman.',
    pdfXlsxLocalSkippedMsg: 'Sesetengah halaman tidak ditukar kepada sel',
    pdfXlsxLocalSkippedDetail:
      'Halaman {pages} tidak dapat ditukar kepada sel; helaiannya mengandungi baris makluman.',
    pdfDocxLocalScannedMsg: 'Dokumen imbasan dikesan',
    pdfDocxLocalScannedDetail:
      'Penukaran setempat mengeksport halaman sebagai imej untuk mengekalkan rupanya. Untuk teks boleh edit, gunakan penukaran awan (dengan OCR).',
    pdfDocxLocalDegradedMsg: 'Sesetengah halaman dieksport sebagai imej',
    pdfDocxLocalDegradedDetail:
      'Halaman {pages} tidak dapat dibina semula dengan pasti dan telah dieksport sebagai imej halaman penuh.',
    pdfDocxLocalOcrMsg: 'Halaman imbasan ditukar kepada teks boleh edit',
    pdfDocxLocalOcrDetail:
      'Halaman {pages} ialah imbasan; teksnya dipulihkan dengan OCR setempat. Sila semak hasilnya.',
    pdfDocxLocalEncryptedDetail:
      'PDF ini disulitkan dan tidak dapat dibuka tanpa kata laluan yang betul.',
    pdfDocxLocalUnsupportedEncDetail:
      'PDF ini menggunakan penyulitan berasaskan sijil atau penyulitan yang tidak disokong dan tidak boleh ditukar secara setempat. Cuba penukaran awan.',
    pdfPwdTitle: 'Masukkan Kata Laluan',
    pdfPwdPrompt: 'PDF ini disulitkan. Masukkan kata laluan untuk membukanya:',
    pdfPwdRetryPrompt: 'Kata laluan salah. Sila cuba lagi.',
    pdfPwdOk: 'OK',
    pdfPwdVerifying: 'Mengesahkan kata laluan…',
    pdfPwdLabel: 'Kata laluan',
    pdfPwdPlaceholder: 'Masukkan kata laluan buka',
    pdfPwdShow: 'Tunjukkan kata laluan',
    pdfPwdHide: 'Sembunyikan kata laluan',
    pdfDocxLocalCorruptDetail: 'Fail rosak atau bukan PDF yang sah dan tidak dapat ditukar.',
    dlgPickSaveDir: 'Pilih Lokasi Simpanan Lalai',
    errSaveDirUnusable:
      'Folder yang dipilih tidak boleh ditulis dan tidak dapat digunakan sebagai lokasi simpanan lalai',
  },
  he: {
    menuFile: 'קובץ',
    menuSectionNew: 'חדש',
    untitledDeck: 'קנבס ללא שם',
    menuNewSlide: 'קנבס חדש',
    menuExportPdf: 'ייצוא כ-PDF…',
    menuOpenInDocs: 'המרה ופתיחה ב-Docs',
    menuPrint: 'הדפסה…',
    menuOpen: 'פתיחה…',
    menuSave: 'שמירה',
    menuSaveAs: 'שמירה בשם…',
    menuClose: 'סגירה',
    menuEdit: 'עריכה',
    menuWindow: 'חלון',
    menuHome: 'דף הבית',
    backToHome: 'חזרה לדף הבית',
    dlgOpenTitle: 'פתיחת קובץ',
    filterSupported: 'קבצים נתמכים',
    errBadArgs: 'ארגומנטים לא חוקיים',
    errBadName: 'שם קובץ לא חוקי',
    errMissing: 'הקובץ לא נמצא',
    errExists: 'כבר קיים קובץ באותו שם',
    errRenameFailed: 'שינוי השם נכשל',
    errNewTabFailed: 'יצירת המסמך החדש נכשלה',
    errUnsupportedExt: 'קובצי .{ext} אינם נתמכים',
    copySuffix: 'עותק',
    menuHelp: 'עזרה',
    thirdPartyNotices: 'הודעות על תוכנות צד שלישי',
    menuExportDocx: 'ייצוא כ-Word…',
    btnCancel: 'ביטול',
    pdfDocxFailedMsg: 'הייצוא כ-Word נכשל',
    pdfDocxBusyMsg: 'ייצוא ל-Word כבר מתבצע. נא להמתין לסיומו.',
    menuExportDocxLocal: 'ייצוא כ-Word (המרה מקומית)…',
    menuExportPptx: 'ייצוא כ-PowerPoint…',
    pdfPptxFailedMsg: 'הייצוא כ-PowerPoint נכשל',
    pdfPptxBusyMsg: 'ייצוא כבר מתבצע. יש להמתין לסיומו.',
    pdfPptxLocalScannedDetail: 'כל עמוד יוצא כתמונה; הטקסט בשקופיות אינו ניתן לעריכה.',
    menuExportXlsx: 'ייצוא כ-Excel…',
    pdfXlsxFailedMsg: 'הייצוא כ-Excel נכשל',
    pdfXlsxBusyMsg: 'ייצוא כבר מתבצע. יש להמתין לסיומו.',
    pdfXlsxLocalScannedDetail:
      'עמודים סרוקים אינם ניתנים להמרה לתאים; בגיליון של כל עמוד נוספה שורת הודעה.',
    pdfXlsxLocalSkippedMsg: 'חלק מהעמודים לא הומרו לתאים',
    pdfXlsxLocalSkippedDetail:
      'לא ניתן היה להמיר את העמודים {pages} לתאים; בגיליונות שלהם נוספה שורת הודעה.',
    pdfDocxLocalScannedMsg: 'זוהה מסמך סרוק',
    pdfDocxLocalScannedDetail:
      'ההמרה המקומית ייצאה את העמודים כתמונות כדי לשמר את המראה. לטקסט הניתן לעריכה, השתמשו בהמרה בענן (עם OCR).',
    pdfDocxLocalDegradedMsg: 'חלק מהעמודים יוצאו כתמונות',
    pdfDocxLocalDegradedDetail:
      'לא ניתן היה לשחזר באופן אמין את עמודים {pages}, והם יוצאו כתמונות של עמוד מלא.',
    pdfDocxLocalOcrMsg: 'עמודים סרוקים הומרו לטקסט הניתן לעריכה',
    pdfDocxLocalOcrDetail:
      'עמודים {pages} היו סריקות; הטקסט שוחזר באמצעות OCR מקומי. מומלץ להגיה את התוצאה.',
    pdfDocxLocalEncryptedDetail: 'קובץ PDF זה מוצפן ולא ניתן היה לפתוח אותו ללא הסיסמה הנכונה.',
    pdfDocxLocalUnsupportedEncDetail:
      'קובץ PDF זה משתמש בהצפנה מבוססת אישורים או בהצפנה שאינה נתמכת ולא ניתן להמירו מקומית. נסו את ההמרה בענן.',
    pdfPwdTitle: 'הזנת סיסמה',
    pdfPwdPrompt: 'קובץ PDF זה מוצפן. הזינו את הסיסמה כדי לפתוח אותו:',
    pdfPwdRetryPrompt: 'סיסמה שגויה. נסו שוב.',
    pdfPwdOk: 'אישור',
    pdfPwdVerifying: 'מאמת את הסיסמה…',
    pdfPwdLabel: 'סיסמה',
    pdfPwdPlaceholder: 'הזינו את סיסמת הפתיחה',
    pdfPwdShow: 'הצג סיסמה',
    pdfPwdHide: 'הסתר סיסמה',
    pdfDocxLocalCorruptDetail: 'הקובץ פגום או שאינו PDF תקין ולא ניתן להמירו.',
    dlgPickSaveDir: 'בחירת מיקום שמירה כברירת מחדל',
    errSaveDirUnusable:
      'התיקייה שנבחרה אינה ניתנת לכתיבה ולא ניתן להשתמש בה כמיקום שמירה כברירת מחדל',
  },
  hi: {
    menuFile: 'फ़ाइल',
    menuSectionNew: 'नया',
    untitledDeck: 'बिना शीर्षक कैनवास',
    menuNewSlide: 'नया कैनवास',
    menuExportPdf: 'PDF के रूप में निर्यात…',
    menuOpenInDocs: 'Docs में बदलें और खोलें',
    menuPrint: 'प्रिंट करें…',
    menuOpen: 'खोलें…',
    menuSave: 'सहेजें',
    menuSaveAs: 'इस रूप में सहेजें…',
    menuClose: 'बंद करें',
    menuEdit: 'संपादन',
    menuWindow: 'विंडो',
    menuHome: 'होम',
    backToHome: 'होम पर वापस जाएँ',
    dlgOpenTitle: 'फ़ाइल खोलें',
    filterSupported: 'समर्थित फ़ाइलें',
    errBadArgs: 'अमान्य आर्ग्युमेंट',
    errBadName: 'अमान्य फ़ाइल नाम',
    errMissing: 'फ़ाइल नहीं मिली',
    errExists: 'इस नाम की फ़ाइल पहले से मौजूद है',
    errRenameFailed: 'नाम बदलने में विफल',
    errNewTabFailed: 'नया दस्तावेज़ बनाने में विफल',
    errUnsupportedExt: '.{ext} फ़ाइलें समर्थित नहीं हैं',
    copySuffix: 'प्रतिलिपि',
    menuHelp: 'सहायता',
    thirdPartyNotices: 'तृतीय-पक्ष सॉफ़्टवेयर सूचनाएँ',
    menuExportDocx: 'Word के रूप में निर्यात करें…',
    btnCancel: 'रद्द करें',
    pdfDocxFailedMsg: 'Word के रूप में निर्यात विफल रहा',
    pdfDocxBusyMsg: 'Word के रूप में निर्यात पहले से चल रहा है। कृपया पूरा होने तक प्रतीक्षा करें।',
    menuExportDocxLocal: 'Word के रूप में निर्यात करें (लोकल)…',
    menuExportPptx: 'PowerPoint के रूप में निर्यात करें…',
    pdfPptxFailedMsg: 'PowerPoint के रूप में निर्यात विफल रहा',
    pdfPptxBusyMsg: 'एक निर्यात पहले से चल रहा है। कृपया उसके पूरा होने की प्रतीक्षा करें।',
    pdfPptxLocalScannedDetail:
      'प्रत्येक पृष्ठ छवि के रूप में निर्यात किया गया; स्लाइड का टेक्स्ट संपादन योग्य नहीं है।',
    menuExportXlsx: 'Excel के रूप में निर्यात करें…',
    pdfXlsxFailedMsg: 'Excel के रूप में निर्यात विफल रहा',
    pdfXlsxBusyMsg: 'एक निर्यात पहले से चल रहा है। कृपया उसके पूरा होने की प्रतीक्षा करें।',
    pdfXlsxLocalScannedDetail:
      'स्कैन किए गए पेज सेल में परिवर्तित नहीं किए जा सकते; प्रत्येक पेज की वर्कशीट में एक सूचना पंक्ति जोड़ी गई है।',
    pdfXlsxLocalSkippedMsg: 'कुछ पेज सेल में परिवर्तित नहीं हुए',
    pdfXlsxLocalSkippedDetail:
      'पेज {pages} सेल में परिवर्तित नहीं किए जा सके; उनकी वर्कशीट में एक सूचना पंक्ति जोड़ी गई है।',
    pdfDocxLocalScannedMsg: 'स्कैन किया गया दस्तावेज़ मिला',
    pdfDocxLocalScannedDetail:
      'लोकल रूपांतरण ने पृष्ठों का स्वरूप बनाए रखने के लिए उन्हें छवियों के रूप में निर्यात किया। संपादन योग्य टेक्स्ट के लिए क्लाउड रूपांतरण (OCR सहित) का उपयोग करें।',
    pdfDocxLocalDegradedMsg: 'कुछ पृष्ठ छवियों के रूप में निर्यात किए गए',
    pdfDocxLocalDegradedDetail:
      'पृष्ठ {pages} का लेआउट विश्वसनीय रूप से पुनर्निर्मित नहीं हो सका, इसलिए उन्हें पूर्ण-पृष्ठ छवियों के रूप में निर्यात किया गया।',
    pdfDocxLocalOcrMsg: 'स्कैन किए गए पृष्ठ संपादन योग्य टेक्स्ट में बदले गए',
    pdfDocxLocalOcrDetail:
      'पृष्ठ {pages} स्कैन थे; स्थानीय OCR से टेक्स्ट पुनर्प्राप्त किया गया। कृपया परिणाम जाँचें।',
    pdfDocxLocalEncryptedDetail:
      'यह PDF एन्क्रिप्टेड है और सही पासवर्ड के बिना इसे खोला नहीं जा सका।',
    pdfDocxLocalUnsupportedEncDetail:
      'यह PDF प्रमाणपत्र-आधारित या असमर्थित एन्क्रिप्शन का उपयोग करता है और इसे स्थानीय रूप से परिवर्तित नहीं किया जा सकता। क्लाउड रूपांतरण आज़माएँ।',
    pdfPwdTitle: 'पासवर्ड दर्ज करें',
    pdfPwdPrompt: 'यह PDF एन्क्रिप्टेड है। खोलने के लिए पासवर्ड दर्ज करें:',
    pdfPwdRetryPrompt: 'पासवर्ड गलत है। कृपया फिर से प्रयास करें।',
    pdfPwdOk: 'ठीक है',
    pdfPwdVerifying: 'पासवर्ड सत्यापित किया जा रहा है…',
    pdfPwdLabel: 'पासवर्ड',
    pdfPwdPlaceholder: 'खोलने का पासवर्ड दर्ज करें',
    pdfPwdShow: 'पासवर्ड दिखाएँ',
    pdfPwdHide: 'पासवर्ड छिपाएँ',
    pdfDocxLocalCorruptDetail:
      'फ़ाइल क्षतिग्रस्त है या मान्य PDF नहीं है, इसलिए रूपांतरण नहीं हो सकता।',
    dlgPickSaveDir: 'डिफ़ॉल्ट सहेजने का स्थान चुनें',
    errSaveDirUnusable:
      'चयनित फ़ोल्डर में लिखा नहीं जा सकता, इसलिए इसे डिफ़ॉल्ट सहेजने के स्थान के रूप में उपयोग नहीं किया जा सकता',
  },
  'zh-TW': {
    menuFile: '檔案',
    menuSectionNew: '新增',
    untitledDeck: '未命名畫布',
    menuNewSlide: '新增畫布',
    menuExportPdf: '匯出為 PDF…',
    menuOpenInDocs: '轉換為 Docs 文件並開啟',
    menuPrint: '列印…',
    menuOpen: '開啟…',
    menuSave: '儲存',
    menuSaveAs: '另存新檔…',
    menuClose: '關閉',
    menuEdit: '編輯',
    menuWindow: '視窗',
    menuHome: '首頁',
    backToHome: '返回首頁',
    dlgOpenTitle: '開啟檔案',
    filterSupported: '支援的檔案',
    errBadArgs: '參數無效',
    errBadName: '檔案名稱不合法',
    errMissing: '檔案不存在',
    errExists: '同名檔案已存在',
    errRenameFailed: '重新命名失敗',
    errNewTabFailed: '新建文件失敗',
    errUnsupportedExt: '暫不支援 .{ext} 類型',
    copySuffix: '副本',
    menuHelp: '說明',
    thirdPartyNotices: '第三方軟體聲明',
    menuExportDocx: '匯出為 Word…',
    btnCancel: '取消',
    pdfDocxFailedMsg: '匯出為 Word 失敗',
    pdfDocxBusyMsg: '正在轉換中，請等待目前的匯出完成。',
    menuExportDocxLocal: '匯出為 Word（本機轉換）…',
    menuExportPptx: '匯出為 PPT…',
    pdfPptxFailedMsg: '匯出為 PPT 失敗',
    pdfPptxBusyMsg: '正在轉換中，請等待目前匯出完成。',
    pdfPptxLocalScannedDetail: '本機轉換已將各頁以圖片保真匯出，簡報中的文字無法編輯。',
    menuExportXlsx: '匯出為 Excel…',
    pdfXlsxFailedMsg: '匯出為 Excel 失敗',
    pdfXlsxBusyMsg: '正在轉換中，請等待目前匯出完成。',
    pdfXlsxLocalScannedDetail: '掃描頁無法轉換為儲存格，對應工作表中已寫入提示列。',
    pdfXlsxLocalSkippedMsg: '部分頁面未轉換為儲存格',
    pdfXlsxLocalSkippedDetail: '第 {pages} 頁無法轉換為儲存格，對應工作表中已寫入提示列。',
    pdfDocxLocalScannedMsg: '偵測到掃描文件',
    pdfDocxLocalScannedDetail:
      '本機轉換已將各頁以圖片方式保真匯出。如需可編輯的文字，請使用雲端轉換（支援 OCR）。',
    pdfDocxLocalDegradedMsg: '部分頁面已以圖片匯出',
    pdfDocxLocalDegradedDetail: '第 {pages} 頁的版面無法可靠重建，已以整頁圖片保真匯出。',
    pdfDocxLocalOcrMsg: '掃描頁已轉換為可編輯文字',
    pdfDocxLocalOcrDetail:
      '第 {pages} 頁為掃描件，已透過本機 OCR 辨識為可編輯文字，建議校對辨識結果。',
    pdfDocxLocalEncryptedDetail: '此 PDF 已加密，未提供正確的密碼，無法轉換。',
    pdfDocxLocalUnsupportedEncDetail:
      '該檔案使用憑證加密或不支援的加密方式，無法在本機轉換，可嘗試雲端轉換。',
    pdfPwdTitle: '輸入密碼',
    pdfPwdPrompt: '此 PDF 已加密，請輸入開啟密碼：',
    pdfPwdRetryPrompt: '密碼不正確，請重試。',
    pdfPwdOk: '確定',
    pdfPwdVerifying: '正在驗證密碼…',
    pdfPwdLabel: '密碼',
    pdfPwdPlaceholder: '輸入開啟密碼',
    pdfPwdShow: '顯示密碼',
    pdfPwdHide: '隱藏密碼',
    pdfDocxLocalCorruptDetail: '檔案已損壞或不是有效的 PDF，無法轉換。',
    dlgPickSaveDir: '選擇預設儲存位置',
    errSaveDirUnusable: '所選資料夾無法寫入，無法作為預設儲存位置',
  },
})

export type HomeStringKey = Parameters<typeof homeI18n>[1]
